---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 2
  Torrent:
    style: row
    columns: 2
  Network:
    style: row
    columns: 4
  Indexers:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2
  Bookmarks:
    style: row
    columns: 4

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

cardBlur: xs # xs, md, etc... see https:/ /tailwindcss.com/docs/backdrop-blur

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"