---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 2
  Torrent:
    style: row
    columns: 2
  Network:
    style: row
    columns: 4
  Indexers:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2
  Bookmarks:
    style: row
    columns: 4

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
